<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_uppdateraTimData" Id="{4ff69180-a805-4dbf-b9fc-9e22289621be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_uppdateraTimData
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>